### PR TITLE
[+++++] Port it to Nan2, now it works on 0.8, 0.10, 0.12 and 4.0

### PR DESCRIPTION
**Pull request by h0x91b**

### CODE REVIEW

**Comment by davidvgalbraith** [comment]
+1

**Comment by davidvgalbraith** [comment]
Hey @h0x91b what are the chances this gets merged some time soon?

**Comment by h0x91b** [comment]
On this week I will do it

**Comment by h0x91b** [comment]
@davidvgalbraith merged, looks fine on my env, can you please check if it works for you too?

**Comment by davidvgalbraith** [comment]
Working great on my end, thank you!

**Comment by h0x91b** [comment]
Cool :)

I will update my servers very soon to new LTS node 4, so if you see that driver do something wrong please tell me.

BTW if you need HGETALL HMGET and HMSET which works with objects you can take code from my fast-redis-cluster driver, this driver a part of it...

**Pull request merged**
